version: "3.2"

services:
  fss-public-api:
    image: fss-public-api
    build:
      context: LBHFSSPublicAPI/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=testdb;Username=postgres;Password=mypassword
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  fss-public-api-test:
    image: fss-public-api-test
    build:
      context: .
      dockerfile: LBHFSSPublicAPI.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
      - ASPNETCORE_ENVIRONMENT=Test
    links:
      - test-database
  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 6543:5432
    env_file:
      - database.env
