sonar.projectKey=LBHackney-IT_lbh-fss-public-api
sonar.organization=lbhackney-it
sonar.sources=LBHFSSPublicAPI
sonar.tests=LBHFSSPublicAPI.Tests
sonar.test.inclusions=LBHFSSPublicAPI.Tests/**
sonar.exclusions=LBHFSSPublicAPI.Tests/**

# OpenCover from build-and-test Report step (paths rewritten from /app/ to workspace)
sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
