sonar.projectKey=LBHackney-IT_lbh-fss-public-api
sonar.organization=lbhackney-it
sonar.sources=LBHFSSPublicAPI
sonar.tests=LBHFSSPublicAPI.Tests
sonar.test.inclusions=LBHFSSPublicAPI.Tests/**
sonar.exclusions=LBHFSSPublicAPI.Tests/**

# Coverlet OpenCover output from CI (see build-and-test job)
sonar.cs.opencover.reportsPaths=coverage/coverage.opencover.xml
